version: '3'

# NSPCC Data Engineering Pipeline
services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - nspcc_network

  # Airflow Webserver
  airflow-webserver:
    build:
      context: ./docker
      dockerfile: airflow/Dockerfile
    image: custom-airflow:latest
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      AIRFLOW_CONN_SPARK_DEFAULT: 'spark://spark-master:7077'
      AIRFLOW_VAR_S3_BUCKET: 'my-data-bucket'
      AIRFLOW_VAR_JDBC_URL: 'jdbc:postgresql://postgres:5432/airflow'
      AIRFLOW_VAR_DB_USER: 'airflow'
      AIRFLOW_VAR_DB_PASSWORD: 'airflow'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./checkpoint:/opt/airflow/checkpoint
    restart: always
    networks:
      - nspcc_network

  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: ./docker
      dockerfile: airflow/Dockerfile
    image: custom-airflow:latest
    command: scheduler
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CONN_SPARK_DEFAULT: 'spark://spark-master:7077'
      AIRFLOW_VAR_S3_BUCKET: 'my-data-bucket'
      AIRFLOW_VAR_JDBC_URL: 'jdbc:postgresql://postgres:5432/airflow'
      AIRFLOW_VAR_DB_USER: 'airflow'
      AIRFLOW_VAR_DB_PASSWORD: 'airflow'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./checkpoint:/opt/airflow/checkpoint
    restart: always
    networks:
      - nspcc_network

  # Airflow Triggerer
  airflow-triggerer:
    build:
      context: ./docker
      dockerfile: airflow/Dockerfile
    image: custom-airflow:latest
    command: triggerer
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./checkpoint:/opt/airflow/checkpoint
    restart: always
    networks:
      - nspcc_network

  # Airflow Initialization
  airflow-init:
    build:
      context: ./docker
      dockerfile: airflow/Dockerfile
    image: custom-airflow:latest
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create --username airflow --firstname Airflow --lastname Admin \
          --role Admin --email airflow@example.com --password airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./checkpoint:/opt/airflow/checkpoint
    restart: on-failure
    networks:
      - nspcc_network

  # Spark Master
  spark-master:
    build:
      context: ./docker
      dockerfile: spark/Dockerfile
    image: custom-spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - ./checkpoint:/opt/bitnami/spark/checkpoint
      - ./config.json:/opt/bitnami/spark/config.json
    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/airflow
      - DB_USER=airflow
      - DB_PASSWORD=airflow
    ports:
      - "9090:8080"
      - "9077:7077"
    networks:
      - nspcc_network

  # Spark Workers (using template)
  spark-worker-1:
    build:
      context: ./docker
      dockerfile: spark/Dockerfile
    image: custom-spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - ./checkpoint:/opt/bitnami/spark/checkpoint
      - ./config.json:/opt/bitnami/spark/config.json
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - JDBC_URL=jdbc:postgresql://postgres:5432/airflow
      - DB_USER=airflow
      - DB_PASSWORD=airflow
    networks:
      - nspcc_network

  spark-worker-2:
    build:
      context: ./docker
      dockerfile: spark/Dockerfile
    image: custom-spark:latest
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - ./checkpoint:/opt/bitnami/spark/checkpoint
      - ./config.json:/opt/bitnami/spark/config.json
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - JDBC_URL=jdbc:postgresql://postgres:5432/airflow
      - DB_USER=airflow
      - DB_PASSWORD=airflow
    networks:
      - nspcc_network

  # Streamlit Dashboard
  streamlit:
    build:
      context:  .
      dockerfile: docker/streamlit/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=airflow
      - DB_USER=airflow
      - DB_PASSWORD=airflow
    volumes:
      - ./streamlit:/app
    working_dir: /opt/app
    networks:
      - nspcc_network

volumes:
  postgres-db-volume:

networks:
  nspcc_network:
    driver: bridge